<?php

return [
    'DIRECTORS_APPROVAL_STAGE_ID' => 'C1:UC_HJL9ZN',
    'TRANSFER_IN_PROGRESS_STAGE_ID' => 'C1:UC_LKP13Z',
    'TRANSFERRED_STAGE_ID' => 'C1:UC_ELVFT8',
    'SECONDARY_ENTITY_TYPE_ID' => 1060,
    'AVAILABILITY_PIPELINE_ID' => 13,
];
