<?php

return [
    'DIRECTORS_APPROVAL_STAGE_ID' => 'C27:PREPAYMENT_INVOIC',
    'TRANSFER_IN_PROGRESS_STAGE_ID' => 'C27:EXECUTING',
    'SECONDARY_ENTITY_TYPE_ID' => 1406,
    'AVAILABILITY_PIPELINE_ID' => 211,
];
